version: '2.1'
services:

  mr-api:
    restart: always
    container_name: mr-api
    build: ./target/docker
    image: messagerelay

  mr-mysql:
    restart: always
    container_name: mr-mysql
    image: "mysql"
    environment:
      - MYSQL_DATABASE=messagerelay
      - MYSQL_USER=messagerelay
      - MYSQL_PASSWORD=messagerelayPW!
      - MYSQL_ROOT_PASSWORD=SuperSecretPassword!@
